version: '3.8'
services:
  todo:
    build: . # Build from local image
    restart: always
    ports:
      - '3000:3000' # Expose docker port to 3000
    expose:
      - '3000'
    volumes:
      - todo:/var/app/todo

volumes:
  todo: