version: '0.1.0'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'wahyou'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'aezakmi321'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'aezakmi321'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_todo:/var/lib/mysql

volumes:
  db_todo: